# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fbad10c97cd84acce0ca498ae0bbe8d8b9ca332467a42937d03a48e219dda7498123b4fa7c8d8c882acd9dffccf6775dc3d3fd45210290ec0490a574af1301e

test:
  secret_key_base: 0425f00e67b4e5375ab29cc8c34238084209d5adabd6513569e017e65459c77a40d36c8f594f7faff0d79ef5f0536f9dcc4a8f5bd1f9feee259733385019b86c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
